eureka:
  client:
   register-with-eureka: true #since it needs to interact with the eureka server
   fetch-registry: true
   service-url:
    defaultZone: http://localhost:8761/eureka/ #defines where to connect to eureka server
  instance:
   hostname: localhost
